APP_NAME: seipee
SHORT_PROJECT_NAME: seipee
APP_KEY: 'base64:NseEglC/fFVhSl8vkfwzDIrYU0oQ3B4EZ+58XLtgVcU='
APP_LOCALE: it
LOG_CHANNEL: daily
FILESYSTEM_DRIVER: local
ACTIVE_THEME: Puro

DATABASE_TYPE: mysql
DB_CONNECTION: mysql

NODE_VERSION: 18
MYSQL_VERSION: '8.0'
PGSQL_VERSION: 15
MARIADB_VERSION: 11.1.2

APP_CODE_PATH_CONTAINER: /var/www/html
