APP_ENV: production
APP_DEBUG: false
DEBUGBAR_ENABLED: false
FORCE_MAIL_SETTING: true
APP_URL: 'https://seipee.it'
BROADCAST_DRIVER: log
CACHE_DRIVER: file
QUEUE_CONNECTION: sync
SESSION_DRIVER: file

RESTART_POLICY: "unless-stopped"

ENABLE_REDIS: false
ENABLE_QUEUE: false
ENABLE_MAILPIT: false

SAIL_XDEBUG_MODE: 'off'
