$ANSIBLE_VAULT;1.1;AES256
38623437363634316438376631366334303761336266346662663163643038663565663266306136
3434613431306666613065373839383037316338396330320a366666383561386562316663393031
62343466393561373962613138653435366561343030356133343938353935393362616131326333
6332666439666339640a613234636636383539636363383133643530633862386565663334633963
33616637316163646363633236653463653366383763626665643736643031613934636132393566
36653633343366663762316639643664653032306434326164313036346164376330353265366238
35353933323063346533323132613962623738633661393830643931643535366133636264343838
61373231643838656633303430393865666465363034613465333461636565643438666432656563
32396662653434333164613530613530396232326563326366303064306132356238303463383530
63373635336631383132616635366333633333643435396232626339306363633666623135616339
64306536616435303166656438313537333339653765346433323263326138653237303531336638
38613236393534363230
