$ANSIBLE_VAULT;1.1;AES256
65363563303139333631383561656662356536373935386234303438646136346661326661373361
3561373163383864343231623037613663396137653534380a346365326332373461656561393737
30356232326535383964613836366534373063373339313163353833353239373139663266366236
6362653865653263380a376332313961613664646530653834306532613962343764313734626636
61386539383566613839626163383564353865376163313334306466373431613233346461653631
31666638643035646236663138333936346333303039666163363566366137616433616131346534
38316266343161656435356634383533333962346634363162653435633564653337383437323635
36393535323362323963363661643761323764393433626338323937626537343161653133613831
30313564626437383164303666656463336336333961316439633964643739383065306232633733
38386661376639633565653636303364336564623763313739616336323934623730356165326231
623336656362646264393337373566643631
